// LOCALHOST 

### GET 
http://localhost:8080/contacts

### GET by ID
 http://localhost:8080/contacts/63bb1e2d9a50a89d18c8933f 

 ### GET by ID
 http://localhost:8080/contacts/63bb1e4b9a50a89d18c89340 

### GET by ID
 http://localhost:8080/contacts/63bb1e659a50a89d18c89341

// PRODUCTION Deploy 

### GET 
https://cse341-personal-w02.onrender.com/contacts 

### GET by ID
https://cse341-personal-w02.onrender.com/contacts/63bb1e2d9a50a89d18c8933f 

### GET by ID
https://cse341-personal-w02.onrender.com/contacts/63bb1e4b9a50a89d18c89340 

### GET by ID
https://cse341-personal-w02.onrender.com/contacts/63bb1e659a50a89d18c89341
